### ISSUE TITLE
ERROR: no HTTP response from

### ISSUE THREAD

**Issue by mirteattack111** [mitre-attack/attack-navigator#102]
When trying to pull a layer.json file from a remote source, an error occurs:
ERROR: no HTTP response from http://some.web.site/layer.json

Using the debugging tools in the browser, I can clearly see that the layer.json is accessed with a 200 OK from the remote server.

**Comment by isaisabel** [comment]
Hi @mirteattack111,

This is an issue with the fact that the request was done over HTTP while Navigator itself is hosted on HTTPS. This is called a [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) request which is disallowed by most browsers for security reasons.

I'll open an issue to improve warnings/errors about mixed-content requests so that it's more obvious what's going on in the future.
