### ISSUE TITLE
layer composition doesn't allow for gradient selection

### ISSUE THREAD

**Issue by z3ndrag0n-cust-n0** [mitre-attack/attack-navigator#121]
Say you're composing layers for a coverage map (attacks, logs, detections). If you assign base 2 score values, and use a suitable gradient you can nicely represent coverage. However if you want to maintain the layers separately, and create a layer from them in the navigator, you can't because there is no option to select the gradient from an existing layer in "Create Layer from other layers."

**Comment by isaisabel** [comment]
Hi @z3ndrag0n-cust-n0,

This feature has been implemented for the upcoming v3.1 release. You can preview it by checking out the `feature/subtechniques-3.1` branch. We'll hopefully get this on develop (and [the beta Navigator](https://mitre-attack.github.io/attack-navigator/beta/enterprise/)) pretty soon since there's not too much left in the [v3.1 milestone](https://github.com/mitre-attack/attack-navigator/milestone/4). 

It'll go live on the master branch sometime around July once the beta is released. You can read more about the sub-techniques beta [here](https://medium.com/mitre-attack/attack-subs-what-you-need-to-know-99bce414ae0b) if you're interested.
