### ISSUE TITLE
Customizing the Navigator via STIX JSON

### ISSUE THREAD

**Issue by izysec** [mitre-attack/attack-navigator#152]
Hi,

Firstly, awesome framework! Just had a quick question regarding running the navigator locally. I'm running the enterprise-navigator off a local JSON file, the original enterprise-attack.json found [here](https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json).

However, I realize that some techniques mentioned in the JSON file don't show up in the navigator when deployed. A few of them are
Web session cookie
Cloud instance metadata API
Credential in files
Cloud service dashboard
Data from cloud storage object

There may be more but these are what I found so far. I tried reading documentation online but didn't find anything answering this. I used the [cti-stix-validator](https://github.com/oasis-open/cti-stix-validator) to check if the JSON is valid. While it did throw me several warnings and a few errors (regarding some cited URL formats), none of them seemed to answer this for me. 

I apologize, but am I missing something?

**Comment by isaisabel** [comment]
Hi @izysec,

There are a few reasons why particular techniques may not show up in the Navigator:
1. The technique may be deprecated or revoked. In the STIX data it would have the property `x_mitre_deprecated: true` or `revoked: true`. Deprecated and revoked objects are no longer maintained by ATT&CK but we keep them around in the data so that they don't break people's workflows.
2. They may be hidden under the initial filter. This is the case with `Cloud instance metadata API` -- the Navigator doesn't show the cloud platforms by default, and that technique is only present on cloud platforms. In the filters dropdown enable the cloud platforms and it should be visible.

For the examples you posted above:
1. `Web session cookie` showed up just fine for me when I searched for it, not sure what happened there.
2. `Cloud instance metadata API` was a case of the initial platform selection hiding it, it was there once I enabled the cloud platforms.
3. `Credential in files` was misspelled (it should be `credentials` -- plural). 
4. `Cloud service dashboard` is again the platform issue.
5. `Data from cloud storage object` is again the platform issue

So the only one I couldn't reproduce was web session cookie. Maybe you misspelled or overlooked it? I used the search interface to find all of the techniques since scanning the table is a bit arduous.

<img width="1666" alt="Screen Shot 2020-04-23 at 8 01 14 AM" src="https://user-images.githubusercontent.com/28868888/80097050-a1f3e580-8538-11ea-9216-2b741e718e78.png">
.

**Comment by izysec** [comment]
Hi Isabel! 

Thanks for your quick response. And yes, this was helpful, it now works. The platform filter was what I missed out. And in the case of credentials in files, I made an error in the JSON file itself.

To keep  the cloud platform filters enabled by default, I've modified the /nav-app/src/app/viewmodels.service.ts file to include cloud platforms by default. Is this the right way to do it or do you see a better way?

Thanks very much for your help!

**Comment by isaisabel** [comment]
Yeah the best way to set the default platforms is modifying viewmodels.service.
