### ISSUE TITLE
2.1 layer won't load on 2.3.2

### ISSUE THREAD

**Issue by glennbarrett** [mitre-attack/attack-navigator#154]
I have several default layers and was on Navigator 2.2 with my 2.1 layers and they work okay there.  Once I try to load them in Navigator 2.3.2, I am getting the following warning that pops for each tab it's trying to load:

WARNING: Uploaded layer version (2.1) does not match Navigator's layer version (2.2). The layer configuration may not be fully restored.

The layer tab names load after pressing okay, but none of the techniques or other layer data loads.

**Comment by isaisabel** [comment]
Hi @glennbarrett,

It's possible that your platform filters aren't getting parsed correctly. [The platform format was updated in 2.3](https://github.com/mitre-attack/attack-navigator/blob/master/CHANGELOG.md#layer-file-format-changes) and while it _should_ be backwards compatible it's possible something isn't working properly there. Check the filters dropdown — if no platforms are selected nothing will render in the matrix. Simply reselect the platforms and it should start working again.

If the platforms are not the issue, please check your javascript console for errors and post them here if there are any. In Chrome you can view the JS console from the menubar with view > developer > javascript console.

Thanks!

**Comment by glennbarrett** [comment]
It looks like the platforms are selected properly.  In the console it’s actually showing a TAXII fetch error connection timeout.  This is odd because I have the previous version working in the same web root, just a different directory.  I even tried pulling the working versions config directly for 2.3.2 and it’s still getting the timeout.  In the directory for the working prior version the console shows the TAXII fetches without errors.  I have TAXII server enabled = false in the config.json but I guess it’s still getting some info from there.

**Comment by glennbarrett** [comment]
I just tried loading by uploading to the blank new navigator and it still pops the error but loads properly anyway.  I only get the TAXII timeouts in the console and the failure to load if they are configured as default layers in the config.json it looks like

**Comment by isaisabel** [comment]
Can you share the layer file and your config.json so that we can debug? You can obfuscate the layer if need be, e.g randomize the name, description, technique data. 

Version 3.0 of the Navigator (currently in beta — see the develop branch or [the beta instance here](https://mitre-attack.github.io/attack-navigator/beta/enterprise/)) involved a significant rewrite of the backend, so there's a chance that if it's a Navigator bug you're experiencing (and not a configuration issue) it's already been fixed with version 3.0.

**Comment by glennbarrett** [comment]
I think this was some sort of caching issue.  While I was going to collect layers to attach here, I set TAXII enabled to false again in the config and then tried to load navigator in a new browser.  It didn't try to make the TAXII calls in the console that time and everything loaded properly.  If I set TAXII enabled to true again with the default TAXII server in the config, it will give me the timeouts and not load any techniques.

Part of my confusion here is that the TAXII errors appear to be intermittent.  I'm noticing that if I try to only load up to about three default layers, the techniques will load but the javascript console populates with cross-origin read blocking errors for the TAXII fetches.

"Cross-Origin Read Blocking (CORB) blocked cross-origin response" and an error that the request to the MITRE CTI TAXII server from my web app's internal FQDN was blocked by CORS policy.

However, if I try to load up 4 or more default layers as we do in our standard config, I just get the timeouts and no explicit CORS errors.  So as long as I keep TAXII disabled, my 2.3.2 with 9 default layers is now loading fine.

**Comment by isaisabel** [comment]
I haven't been able to replicate the issue on 2.3.2, run using `ng serve` and visited in chrome 81.0.4044.122. 

It is odd that your app is internally blocking CORS, I've never seen that before. The data initialization on version 2.3.2 was poorly implemented — if I remember correctly it fetches data from the TAXII server whenever the tab changes and when each tab is initialized. While I don't understand why the number of initial layers affects your CORS errors I wouldn't be surprised if it was a side effect of the way the app is handling the data.

As I mentioned earlier, version 3 of the application completely rewrote the data-handling side of things so there should only be a single request for the data when the app initializes. Hopefully this also resolves your bug if it was a result of the way we were retrieving the data.

Since a workaround exists (disabling the taxii server and clearing the cached config file) and it's probably resolved in the next version I'm going to close this issue. If you have additional concerns feel free to comment and reopen the issue.
