### ISSUE TITLE
Manual selection of individual sub-techniques doesnt allow color coding

### ISSUE THREAD

**Issue by gertjanbruggink** [mitre-attack/attack-navigator#172]
When manually selecting a subtechnique, it selects the complete set of subtechniques. 

Tested 'only select' and the other selection options, but couldn't make it work when using manual selection.

https://mitre-attack.github.io/attack-navigator/beta/enterprise/

![afbeelding](https://user-images.githubusercontent.com/50614049/83753070-e1e6d600-a669-11ea-9bf7-6343de4a1313.png)

**Comment by isaisabel** [comment]
Hi @gertjanbruggink,

By default, the techniques and sub-techniques are selected together in the Navigator interface. This also includes the selection of sibling sub-techniques if a sub-technique is clicked. You can change this behavior by disabling the "select sub-techniques with parent" control in the "selection behavior" menu:

![image](https://user-images.githubusercontent.com/28868888/83753989-3de53680-a639-11ea-8768-d85f07f61301.png)

In [version 3.1](https://github.com/mitre-attack/attack-navigator/blob/feature/subtechniques-3.1/CHANGELOG.md) we're changing the default behavior so that sub-techniques are selected independantly of their techniques. The control will still exist for those who want to select sub-techniques alongside their parent techniques, but it will default to being unselected.

**Comment by gertjanbruggink** [comment]
Thank you!
