### ISSUE TITLE
Exporting Beta techniques

### ISSUE THREAD

**Issue by nconder** [mitre-attack/attack-navigator#174]
Do we have a way to export (csv or JSON) all [Beta techniques](https://attack.mitre.org/beta/) similar to how its done with [attack-navigator](https://mitre-attack.github.io/attack-navigator/enterprise/)? 
Is there an attack navigator for beta techniques if not when?

**Comment by isaisabel** [comment]
Hi @nconder,

Yes, we have a beta instance of the Navigator which includes the sub-techniques data! 
- The enterprise instance is [here](https://mitre-attack.github.io/attack-navigator/beta/enterprise/).
- The mobile instance is [here](https://mitre-attack.github.io/attack-navigator/beta/mobile/). Mobile doesn't have sub-techniques but there are numerous other improvements that might still be useful to mobile users.
- You can find the beta source code on the develop branch. The changelog for the update is [here](https://github.com/mitre-attack/attack-navigator/blob/develop/CHANGELOG.md).

We also have a WIP beta 2 version which you can find on the `feature/subtechniques-3.1` branch which includes [additional quality-of-life changes](https://github.com/mitre-attack/attack-navigator/blob/feature/subtechniques-3.1/CHANGELOG.md). We don't have a live instance of that version yet however since it's still a work in progress.

Lastly, the STIX data for the sub-techniques beta is available on [our MITRE/CTI repo](https://github.com/mitre/cti/tree/subtechniques).

Please let us know if you have any other questions!
