### ISSUE TITLE
Metadata layout in 3.0/3.1 version

### ISSUE THREAD

**Issue by rubinatorz** [mitre-attack/attack-navigator#189]
Hi @isaisabel 

The layout of the metadata in the new 3.0/3.1 version of the Navigator is slightly changed compared to the 2.0 version. Values are now aligned with each other, the line height of each line is increased and the width of the tooltip is smaller:

<img width="366" alt="Screenshot 2020-06-29 at 17 13 00" src="https://user-images.githubusercontent.com/11735227/86110321-b9fe5d00-bac5-11ea-903a-cbf9637ca2cb.png">

In the previous version it was like this:
<img width="286" alt="Screenshot 2020-06-29 at 17 12 51" src="https://user-images.githubusercontent.com/11735227/86110364-c387c500-bac5-11ea-9ba7-5daa5416899f.png">

I can imagine the choice for this, but in our case it just looks less nice and a bit messy in the new version of the metadata. Is there a chance of having an option to influence this behaviour?

Thanks!

**Comment by isaisabel** [comment]
Hi @rubinatorz,

Sorry, I did see your comment on the other issue yesterday I just haven't had time to respond until now.

The new tooltip implementation uses a borderless table instead of just a line by line listing. This theoretically improves readability although apparently not in your specific case. Two possible ways to improve the readability for your case:
1. remove the bullet points
2. Empty values could be represented as `""` instead of `"-"`. 
3. Remove the section breaks, or represent them as empty keys and values to make a blank line:
   ```json
    { "name": "", "value": ""}
   ```

One thing we could possibly change is setting white-space to `nowrap` for the lefthand side of the key-value pair. This way the metadata name wouldn't wrap when there are multiple words. In practice I'm not sure this actually improves things though:



![Screen Shot 2020-06-30 at 2 33 47 PM](https://user-images.githubusercontent.com/28868888/86164007-18840500-badf-11ea-89ca-747c3887b6f3.png)
above: add the following to line 13 of `nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.scss`:
```scss
        td:first-child {
            white-space: nowrap;
        }
```

![Screen Shot 2020-06-30 at 2 33 15 PM](https://user-images.githubusercontent.com/28868888/86164001-17eb6e80-badf-11ea-9b85-51b490ea8d7f.png)
above: how the same metadata looks with the current implementation.

If you wanted to modify the tooltip template yourself, it should be pretty straightforward to modify `nav-app/src/app/matrix/technique-cell/tooltip/tooltip.component.html` (and the associated SCSS linked above) into a format you find more pleasant. Even if you're not familiar with the ins and outs of Angular the template for the tooltip is quite close to plain HTML.

I'll leave this issue open and marked as "seeking feedback" in case other users want to chime in with their thoughts.

**Comment by marcusbakker** [comment]
@isaisabel having the option `nowrap` would be of great help to allow a different style of formatting. Would it be possible to include this in the official version of the Navigator?

**Comment by rubinatorz** [comment]
Hi @isaisabel 

Thanks for getting back on this. I did indeed put this also in a comment on issue #188, but I thought it might be better to make a separate issue for it.

I tried your suggestions and this helps a bit. However empty names and/or values are not allowed, an error is shown when loading the layer into the Navigator:
<img width="451" alt="Screenshot 2020-07-01 at 14 34 07" src="https://user-images.githubusercontent.com/11735227/86244231-eee2e080-bba7-11ea-8fbb-6c8d3282bb06.png">

Having an option to enter empty names and values is indeed useful to have section breaks. I can use a space in both name as value, but then still a colon is shown.

Regarding the `no-wrap` you suggested: I really love this formatting. So it would be very nice if you could include that in the release.

**Comment by isaisabel** [comment]
Yeah we can include no-wrap on the key as part of the v3.1 release. @clemiller could you please make sure it makes its way into the branch? The change should be in my comment above (the addition to the tooltip SCSS)

@rubinatorz You're right that it doesn't work. [The typechecking we implemented doesn't like empty values on required fields](https://github.com/mitre-attack/attack-navigator/blob/feature/subtechniques-3.1/nav-app/src/app/viewmodels.service.ts#L1480-L1487) (and empty strings are considered an empty value). However, whitespace _does_ work... except that it includes the colon delimiter which I had forgotten about:
![image](https://user-images.githubusercontent.com/28868888/86267332-89392900-bb94-11ea-99b9-d52f75a3a184.png)
```json
"metadata": [
                {
                    "name": "hello",
                    "value": "world"
                }, 
                {
                    "name": " ",
                    "value": " "
                },
                {
                    "name": "how",
                    "value": "goes"
                }
            ],
```

**Comment by isaisabel** [comment]
We can explore adding a section break feature to the metadata format in future updates (the v3.1 deadline is too soon for us to add to that milestone)

**Comment by rubinatorz** [comment]
Hi @isaisabel 

Thanks for planning to incorporate the nowrap in 3.1! Very happy with that!

Regarding the section break, we can for now work around the colon and it would be great to have the section break in the future update.

**Comment by isaisabel** [comment]
The nowrap change has now been implemented in v3.1. I'm leaving this open to document the need for further improvements in that UI, namely allowing section breaks.

**Comment by rubinatorz** [comment]
Looks great @isaisabel and @clemiller! Thanks a lot.

<img width="212" alt="Screenshot 2020-07-02 at 15 01 22" src="https://user-images.githubusercontent.com/11735227/86362063-08059300-bc75-11ea-9911-fb7dff234ba1.png">

We have a temporary workaround for the section break as you can see. Looking forward to a real section break.

**Comment by clemiller** [comment]
Hi all! 

We are implementing the section break feature as a part of the next update (v4.1). We're planning to add the option for a "divider” property, which will add a section break where the property occurs in the list of metadata. This will be shown as a horizontal bar across the table. Before finalizing this implementation, we'd like to seek some feedback. Please feel free to share your thoughts!

 Here's an example of the format:

```
"metadata": [
	{
		"name": "Overlay",
		"value": "Detection"
	},
	{
		"divider": true
	},
	{
		"name": "Applicable to",
		"value": "All"
	},
        ...,
]
```
<img width="250px" src=https://user-images.githubusercontent.com/48832936/97722714-5438d680-1aa1-11eb-8548-36761dc1ab8d.png>

**Comment by rubinatorz** [comment]
Hi @clemiller and @isaisabel, this is great! It looks good and exactly what we need. The way the section break can be inserted looks handy.

**Comment by marcusbakker** [comment]
Hi @clemiller, that looks awesome!

**Comment by clemiller** [comment]
Great, we will go ahead with this implementation for the next release. Thank you everyone!

**Comment by isaisabel** [comment]
The divider feature is now present in the develop branch. We'll be releasing it to the live instance soon.
