### ISSUE TITLE
Translating tactics/techniques/subtechniques

### ISSUE THREAD

**Issue by sergioya** [mitre-attack/attack-navigator#209]
I don’t know this is right place to ask, I would like to develop Japanese translation version of tactics/techniques/subtechniques layer. This navigator is very useful to show TTPs performed in red teaming & purple teaming. However, it’s only English. Is it okay to pull request?

**Comment by isaisabel** [comment]
Hi @sergioya,

Generally we do accept pull requests to this repository. However, translations of ATT&CK is more relevant to the source data itself, which is kept on our [MITRE/CTI](https://github.com/mitre/cti) GitHub repository. Unfortunately I can't transfer this issue to that repo because it belongs to a different GitHub organization (`mitre` instead of `mitre-attack`), but you can feel free to reopen the issue over there if you'd like. 

We can't take pull requests against the source data in that repo because we build it using internal systems, but we do welcome use of the issue tracker over there to document community requests. 

If you were hoping to help with the translation work, I'd recommend emailing our attack@mitre.org mailbox directly. I'm not sure what our contribution guidelines are for that sort of thing ([check out our general contributing info here](https://attack.mitre.org/resources/contribute/)).
