### ISSUE TITLE
Certain techniques are not colored

### ISSUE THREAD

**Issue by mvelazc0** [mitre-attack/attack-navigator#213]
Hello.

When opening a Navigator layer,  when one or more sub-techniques are supported, the technique itself also receives a color. However, some of them dont. 

Simple way of replicating: Create a new layer and pick APT29.

As you can see on the screenshot, while one sub-technique  "PowerShell" is part of the layer , the technique itself "Command and Scripting Interpreter" does not receive color.

![image](https://user-images.githubusercontent.com/4950700/89127586-93648500-d4bc-11ea-8ccb-b2feff379db4.png)

However, thats not the case for "Software Packing" and ""Obfuscation Files or Information" where both are colored

![image](https://user-images.githubusercontent.com/4950700/89127592-9eb7b080-d4bc-11ea-8c48-1dc9d46023d0.png)

I think it would be really helpful to also color the technique even if only a subset of sub techniques are in scope.

Thanks

**Comment by isaisabel** [comment]
Hi @mvelazc0,

The ATT&CK dataset allows groups, software, and mitigations to map to sub-techniques without mapping also to the parent technique, and vice versa. For example, [G0021](https://attack.mitre.org/groups/G0021/) maps to T1566.001 and T1566.002 without mapping to T1566 itself. It also maps to T1140 without mapping to any of T1140's sub-techniques. So the lack of color for the technique when only the sub-technique is mapped is expected behavior since the data model provides that level of granularity in the mappings.

We do recognize that it can in some cases be useful to color the parent technique according to the sub-technique scores. Please see #202 for our plans to implement this feature.
