### ISSUE TITLE
One "source_name" value for S0302 (Twitoor) is incorrect

### ISSUE THREAD

**Issue by nonstoprunning** [mitre-attack/attack-navigator#227]
enterprise-attack.json (in https://github.com/mitre/cti/tree/master/enterprise-attack) contains info about the external_id S0302 (Twitoor)... one of its "source_name" value is "mitre-mobile-attack" when sould be "mitre-attack"
[enterprise-attack.zip](https://github.com/mitre-attack/attack-navigator/files/5174319/enterprise-attack.zip)

**Comment by isaisabel** [comment]
Hi @nonstoprunning,

This was probably an error on our part. [Twitoor is an Android malware but is for some reason only mapped to enterprise techniques](https://attack.mitre.org/software/S0302/). For groups, the mappings determine what bundle(s) it ends up in, so, so because of the enterprise mappings it is in the enterprise bundle. However, it also has the Android platform, which results in the `mitre-mobile-attack` source_name. This will be fixed in our next release.

In the future, this issue would be better opened in the [MITRE/CTI issue tracker](https://github.com/mitre/cti/issues) or submitted [by email](https://attack.mitre.org/resources/contribute/).
