### ISSUE TITLE
Navigator SVG Export Canvas

### ISSUE THREAD

**Issue by diogo-fernan** [mitre-attack/attack-navigator#293]
Hello there,

It looks like the canvas of exported `*.svg` files from navigator (online version) expands for all elements beyond the matrix (not sure why). This causes tools to preview undesired empty space around the matrix. A workaround is to edit the file, ungroup all elements, copy them to a new layer with a new canvas and export that back to a new file.

This behavior can be observed in the following screenshots:

![01](https://user-images.githubusercontent.com/11231644/117802773-c7d84f00-b24d-11eb-97b7-aaab8bf9fd83.png)
![02](https://user-images.githubusercontent.com/11231644/117802778-c870e580-b24d-11eb-8404-3f059c9c923a.png)

Thanks,
Diogo

**Comment by isaisabel** [comment]
Hi @diogo-fernan,

In what program are you seeing the SVG bug? I've had trouble replicating it in Inkscape with my test layers. I also can't see anything in the actual SVG XML that would cause this -- could you upload the actual SVG (not a screenshot) so that I can dig around in the XML and see what's up? Thanks!

**Comment by diogo-fernan** [comment]
The `*.svg` export has been attached as [export.svg.zip](https://github.com/mitre-attack/attack-navigator/files/6494202/export.svg.zip). Note that the tool used is irrelevant because of the following macOS preview that shows the undesired empty space around the matrix before opening it:
<img width="1170" alt="preview" src="https://user-images.githubusercontent.com/11231644/118499691-176fbc80-b71f-11eb-8e50-7d8401d1a082.png">

**Comment by iguannalin** [comment]
> The `*.svg` export has been attached as [export.svg.zip](https://github.com/mitre-attack/attack-navigator/files/6494202/export.svg.zip). Note that the tool used seems to be irrelevant because of the following macOS spacebar preview that shows the undesired empty space around the matrix before opening it:
> <img alt="preview" width="1170" src="https://user-images.githubusercontent.com/11231644/118499691-176fbc80-b71f-11eb-8e50-7d8401d1a082.png">

Hi Diogo!

I opened your attached file in Inkscape and I don't see the empty space around the svg (screenshot below). Do you have a layer JSON file I can use to export to an SVG and recreate this for myself?

<img width="976" alt="Screen Shot 2021-05-26 at 3 05 52 PM" src="https://user-images.githubusercontent.com/32778440/119717423-fcc5d380-be01-11eb-8ca7-896bb5df6a44.png">

**Comment by isaisabel** [comment]
It looks like (reading the raw SVG) the width and height are quite small: 
```
<svg width="415.73125000000005" height="321.24687500000005" [...]
```
This can be reproduced by making the image size really small:
![Screen Shot 2021-05-26 at 3 26 19 PM](https://user-images.githubusercontent.com/28868888/119719492-d2423d80-be36-11eb-8c24-85aa4ceaab42.png)
Which produces a similarly small image when previewed in finder or a web browser:
![Screen Shot 2021-05-26 at 3 26 41 PM](https://user-images.githubusercontent.com/28868888/119719542-e6863a80-be36-11eb-8dd3-734580de1515.png)
Inkscape however scales this to the view instead of using the actual size: 
![image](https://user-images.githubusercontent.com/28868888/119719686-13d2e880-be37-11eb-930d-d10f7f48719f.png)

So this is actually pretty much intended behavior, you selected a small image size when exporting your layer and the preview is thus small. If you select a large image size it should work better when trying to embed the image or use it in other applications. This should also help avoid the overlarge sub-technique triangles which don't scale linearly with image size.

**Comment by diogo-fernan** [comment]
@isaisabel thanks for checking. It is weird nonetheless that my editor shows all that extra space and objects that expand to the right. Perhaps it might be specific to the app.
