### ISSUE TITLE
Enabled sub-techniques are not present in the exported layer

### ISSUE THREAD

**Issue by Still34** [mitre-attack/attack-navigator#312]
Upon enabling a sub-technique, the exported `layer.json` should contain an entry for the sub-technique, yet it is missing from the exported file.

![image](https://user-images.githubusercontent.com/5843208/123215635-a7193f80-d503-11eb-8c47-820beb8d1613.png)

Is this an intended behavior?

**Comment by isaisabel** [comment]
Hi @Still34,

The ATT&CK Navigator omits technique and sub-technique entries which have no annotations (all their annotations are the default values). So if the given sub-technique has no color, comment, metadata, and enabled is `true`, it will not be included in an exported Navigator layer. If you add a test comment or color you'll be able to see it in the output.

This feature makes output layers much smaller since only (sub-)techniques with annotations need to be included. With 552 (sub-)techniques in Enterprise you can imagine how hard to work with layer files would be if all (sub-)techniques were included regardless of annotation!

So yes, this is intended behavior.

**Comment by Still34** [comment]
So hypothetically, if I'm attempting to describe an incident with certain techniques and sub-techniques and wish to export these data, what is the expected behavior from the user?

**Comment by isaisabel** [comment]
It's sort of up to you how to approach it, the Navigator is very flexible in how it can be used. Personally if I were trying to describe the usage of a specific set of techniques I might do some combination of the following:
- Hide all techniques that were not involved in the incident.
- Add colors to the techniques that were involved to make them more apparent, or to categorize them if there are aspects worthy of categorization. If there is numeric data (e.g the frequency of use) I would use scores instead of manually assigned colors.
- Add comments to the techniques that were involved describing their involvement.

If you want to access data for a specific set of techniques and don't really care about the annotation side of things, you may want to check out our STIX repositories which contain the full technique data. The data exported by the Navigator does not contain the full data for techniques, just the name and tactic.
- ATT&CK in STIX 2.0: https://github.com/mitre/cti
- ATT&CK in STIX 2.1: https://github.com/mitre-attack/attack-stix-data
