### ISSUE TITLE
Is API provided?

### ISSUE THREAD

**Issue by StealerCook** [mitre-attack/attack-navigator#332]
Does navigator as web hosted or local instance provide API with which it can be integrated to other platforms? or If not, Do we have any work around for the same?

**Comment by isaisabel** [comment]
Hi @StealerCook,

The ATT&CK Navigator is a clientside only application, so there is no back-end or API to connect to for third-party extensions. However, we do have some additional tools which can be used to replicate ATT&CK Navigator features in an automateable fashion:
- Our [mitreattack-python](https://github.com/mitre-attack/mitreattack-python) pip library can be used to generate, manipulate, and export Layer files in much the same way the Navigator can. Specific interfaces that are replicated there:
    - Export layers to SVG
    - Export layers to Excel
    - Merge layers ("create layer from other layers")
    - WIP: generate layers representing group/software/mitigation mappings
- We also have some standalone generators on our [attack-scripts](https://github.com/mitre-attack/attack-scripts) repo which can generate layer files:
    - [Diff two verisons of the dataset and create a layer representing the changes](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/diff_stix.py)
    - Various example layer generators ([randomized heatmaps](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/layers/samples/heatmap.py), [mappings to groups with "bear" in their name/associated groups](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/layers/samples/bear_APT.py), various layers representing technique usage [[1](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/layers/samples/apt3_apt29_software.py), [2](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/layers/samples/software_execution.py)]).

I believe there are also third party tools for layer generation such as [mitre-assistant](https://github.com/dfirence/mitre-assistant), though I'm not personally familiar with the extent of functionality of that particular library since the ATT&CK team does not maintain it.
