### ISSUE TITLE
Loading json layer using a Javascript API

### ISSUE THREAD

**Issue by jinxka** [mitre-attack/attack-navigator#338]
Is there a way to load a custom json layer without using url fragment #layerURL ?

Is there a Javascript API to do it ?

I want to be able to dynamically change the layer.

**Comment by isaisabel** [comment]
Hi @jinxka,

In addition to loading via URL you can also upload layers from the filesystem. If you want to _programmatically_ load or manipulate layers while the application is running however unfortunately that's not really possible. ATT&CK Navigator is a client-side only application so there's really no API to connect to in order to change layers. Everything has to happen through the user interface. 

I suppose you could always fork the project and extend the codebase to have whatever dynamic layer manipulation you desired, but that'd be pretty tricky depending on what exactly you want to accomplish.

We do however have some other some additional tools which can be used to replicate ATT&CK Navigator features in an automateable fashion:
- Our [mitreattack-python](https://github.com/mitre-attack/mitreattack-python) pip library can be used to generate, manipulate, and export Layer files in much the same way the Navigator can. Specific interfaces that are replicated there:
    - Export layers to SVG
    - Export layers to Excel
    - Merge layers ("create layer from other layers")
    - WIP: generate layers representing group/software/mitigation mappings
- We also have some standalone generators on our [attack-scripts](https://github.com/mitre-attack/attack-scripts) repo which can generate layer files. These could serve as good examples for methodologies for programmatically creating and manipulating layers:
    - [Diff two verisons of the dataset and create a layer representing the changes](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/diff_stix.py)
    - Various example layer generators ([randomized heatmaps](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/layers/samples/heatmap.py), [mappings to groups with "bear" in their name/associated groups](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/layers/samples/bear_APT.py), various layers representing technique usage [[1](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/layers/samples/apt3_apt29_software.py), [2](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/layers/samples/software_execution.py)]).
