### ISSUE TITLE
Navigator toolbar sticks on top: problems with fullpage screenshots

### ISSUE THREAD

**Issue by rubinatorz** [mitre-attack/attack-navigator#358]
hi there!

I love the next 4.4 release where the tabs got a redesign. They now hide automatically when scrolling. The toolbar itself sticks on top and is always visible. Which is great. However when making a fullpage screenshot with for example Firefox:FireShot, the toolbar is visible multiple times, see attachment:
![toolbar-duplicated-on-fullpage-screenshot](https://user-images.githubusercontent.com/11735227/135421249-24317f12-355d-4832-b2a9-ea9350323d59.png)

Is it possible to have an option to disable/enable the stickyness of the toolbar? When making fullpage screenshots it's then possible to turn of that the toolbar stays on top, which results (hopefully) in a nice fullpage screenshot.

Thanks!

**Comment by isaisabel** [comment]
Hi @rubinatorz,

This is a very interesting bug, I wonder why FireShot has this behavior and how it operates behind the scenes. We might be able to disable the sticky tabs using the "create a customized Navigator" feature, reverting the overall scrolling UX to what it was before the most recent update when the feature is disabled. Hopefully the current implementation is similar enough to what it was previously to be able to toggle between the two.

In the meantime, you can probably export the document to SVG instead of using FireShot, which should avoid the header issues. The purpose of the SVG export tool was originally to allow users to capture screenshots of their application since we weren't aware of tools like FireShot back when the Navigator was developed.

**Comment by rubinatorz** [comment]
hi @isaisabel 

I think FireShot automatically scrolls x times vertically through the page and every time it scrolls, the toolbar moves to the top / stays visible. I think it's hard to bypass this, because of the way FireShot works. But is it an option to have an option to disable the stickyness of the tabs/toolbar?

I indeed know of the SVG export function. But I like the pure Navigator overviews more :-)

I tried to do something with "create a customized Navigator". But the downside of this is that you need to load the JSON from a url location, which I haven't available. Almost always I have them locally on my disk.

**Comment by isaisabel** [comment]
Hi @rubinatorz,

> I tried to do something with "create a customized Navigator". But the downside of this is that you need to load the JSON from a url location, which I haven't available. Almost always I have them locally on my disk.

That's not technically true, you can create a customized Navigator without a default layer specified, open the resultant customized hyperlink in a new browser window, and then upload the layer there. 

It's also worth mentioning that if you have the layers locally on disk you could host them using a simple HTTP server (`python3 -m http.server --port 8082`) or put them in the assets folder. You can then access them using a layerURL if that makes your life easier 😄.

Regardless, we'll look into making the sticky toolbar optional for a future release.

**Comment by iguannalin** [comment]
Hi @rubinatorz, though it might not be a direct fix for your issue, per #387 we added a setting in the customized Navigator configurations to turn off the sticky header within the tabs which will prevent it from showing up in fullpage screenshots taken with the FireShot plugin.

**Comment by iguannalin** [comment]
Hi @rubinatorz, though it might not be a direct fix for your issue, per #387 we added a setting in the customized Navigator configurations to turn off the sticky header within the tabs which will prevent it from showing up in fullpage screenshots taken with the FireShot plugin.
