### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported when running the docker image

### ISSUE THREAD

**Issue by rpietzsch** [mitre-attack/attack-navigator#391]
running the built docker image results in error:

```sh
...
de:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/nav-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/nav-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at /nav-app/node_modules/webpack/lib/NormalModule.js:452:10
    at /nav-app/node_modules/webpack/lib/NormalModule.js:323:13
    at /nav-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /nav-app/node_modules/loader-runner/lib/LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (/nav-app/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:48:13)
    at processResource (/nav-app/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/nav-app/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/nav-app/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/nav-app/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/nav-app/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/nav-app/node_modules/webpack/lib/Compilation.js:739:10)
    at /nav-app/node_modules/webpack/lib/Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
...
```

pls. advice. 

Tested with v4.5.4 and v4.4.1, same issue with both version.

**Comment by rpietzsch** [comment]
same with v3.1 and v2.3.2. I guess I am missing something...?

**Comment by isaisabel** [comment]
Likely related to #379 and #356.

**Comment by rpietzsch** [comment]
wtr. #379, the image build in my case runs through fine. Its only when I then try to `docker run -p 4200:4200 yourcustomname`.

**Comment by ManuelYaga** [comment]
I had the same problem and it seems to come from NodeJS 17. Downgrading to NodeJS 16 seems to do the work, at least apparently. Citing: "The reason is here: https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382
node no longer supports md4 as hash function. sha1 might be a good choice for hashing with bundles."

This thread shows the same problem with different solutions: https://github.com/vercel/next.js/issues/30078

Hope it helps.

**Comment by manuelbee** [comment]
I had the same problem and it seems to come from NodeJS 17. Downgrading to NodeJS 16 seems to do the work, at least apparently. Citing: "The reason is here: https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382
node no longer supports md4 as hash function. sha1 might be a good choice for hashing with bundles."

This thread shows the same problem with different solutions: vercel/next.js#30078

Hope it helps.

**Comment by jondricek** [comment]
I just want to chime in and say that we are actively working on this issue still. Just updating the `Dockerfile` to have `FROM node:16` or `FROM node:lts` fixes the build error for me (and others on the team), but like @rpietzsch points out, running the docker container fails with the following (abbreviated) error

```
...
...
...
** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
⠏ Generating browser application bundles (phase: emitting)...
<--- Last few GCs --->

[21:0x50bc300]   149333 ms: Mark-sweep (reduce) 984.3 (1009.8) -> 983.6 (1009.5) MB, 2156.7 / 1.4 ms  (average mu = 0.087, current mu = 0.008) allocation failure scavenge might not succeed
[21:0x50bc300]   149356 ms: Scavenge (reduce) 984.7 (1009.5) -> 984.1 (1009.5) MB, 4.4 / 0.0 ms  (average mu = 0.087, current mu = 0.008) allocation failure
[21:0x50bc300]   149375 ms: Scavenge (reduce) 984.7 (1009.5) -> 984.3 (1010.0) MB, 6.3 / 0.0 ms  (average mu = 0.087, current mu = 0.008) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00d90 node::Abort() [ng serve --host 0.0.0.0]
 2: 0xa1823b node::FatalError(char const*, char const*) [ng serve --host 0.0.0.0]
 3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng serve --host 0.0.0.0]
 4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng serve --host 0.0.0.0]
 5: 0xea6105  [ng serve --host 0.0.0.0]
 6: 0xea6be6  [ng serve --host 0.0.0.0]
 7: 0xeb4b1e  [ng serve --host 0.0.0.0]
 8: 0xeb5560 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng serve --host 0.0.0.0]
 9: 0xeb84de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [ng serve --host 0.0.0.0]
10: 0xe7990a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [ng serve --host 0.0.0.0]
11: 0x11f2f06 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [ng serve --host 0.0.0.0]
12: 0x15e7819  [ng serve --host 0.0.0.0]
Aborted
```

I've tried about 50 different ways of increasing the memory, from setting `NODE_OPTIONS=--max-old-space-size=8192` (as reported in [many](https://support.snyk.io/hc/en-us/articles/360002046418-JavaScript-heap-out-of-memory) [different](https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas) [places](https://sebhastian.com/javascript-heap-out-of-memory/) [across](https://medium.com/the-node-js-collection/node-js-memory-management-in-container-environments-7eb8409a74e8) [the](https://stackoverflow.com/questions/48387040/how-do-i-determine-the-correct-max-old-space-size-for-node-js) [internet](https://github.com/angular/angular-cli/issues/18109)), to upping the Mac Docker Desktop resources from 2GB to 32 GB per container, upping the memory per the individual docker run command (`docker run --memory 512m -p 4200:4200 yourcustomname`), and probably a few others. The best progress I made in there was a few times instead of the above stack trace, it gets:

```
...
...
...
** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
⠏ Generating browser application bundles (phase: emitting)...
Killed
```

Anyway, that's the long way of saying that:

1. it appears there is a memory leak
2. throwing memory at it hasn't solved the issue
3. downgrading to Node 16 (or even 14) doesn't just fix it
4. I'm open to any good ideas that anyone has while we continue to troubleshoot!

**Comment by manuelbee** [comment]
My fault. I am not running the Navigator in a doxker container, sorry for the confusion. I commented because the error message with reference to "ERR_OSSL_EVP_UNSUPPORTED" the was the same I got when building with NodeJ17, and it was solved downgrading Node to v16.

**Comment by jondricek** [comment]
No worries! It is just ending up being a multi-stage effort. Yay rabbit holes!

**Comment by jondricek** [comment]
The pull request above looks like it fixes the issue to me. The two-part issue/solutions play out as follows:

1. The `digital envelope routines` error from @rpietzsch is solvable by switching the `Dockerfile` from using the base Docker image of `node:latest` to `node:16` (the latest LTS at present, which is preferred)
2. The `JavaScript heap out of memory` error was trickier. 6 months ago we added into the `angular.json` file references to markdown files that are in the parent directory (`../`) of `nav-app` (see here: https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/angular.json#L22-L23). This is fine in the local, git cloned environment. But the Dockerfile "simply" copies everything in the `nav-app/` directory into the docker image in `/nav-app/`. Since `../` from there inside the docker container is just `/`, well, JavaScript couldn't handle looking for all `*.md` files on the whole filesystem!

The fix for the latter one, was to:

* Move the `Dockerfile` up to the top of the git repo
* Copy all needed files into the container (`nav-app`, `layers/*.md`, and `*.md`)
* Update the documentation as to where you need to run the `docker` commands from now

This fix does have a change to the innards of the docker image! Files used to be in `/nav-app/` but now they will be in `/src/nav-app/`

I'd like to get some feedback to know if the fix-docker branch is working for someone besides myself before merging it in to the develop branch - I also have someone in mind that may not comment here, so regardless, the fix is on its way!

**Comment by jondricek** [comment]
Alright - I was able to check with a colleague that the pull request worked for them as well. I'll merge in the PR and then close this ticket shortly.
