### ISSUE TITLE
Low value for scoring gradient is not honored

### ISSUE THREAD

**Issue by glennbarrett** [mitre-attack/attack-navigator#416]
I am trying to gradient a set of techniques with score from 100-115 while all other techniques on the board have a score of 0.  When setting a gradient with the low value 100 and high value 115, all techniques with a score <= 100 are colored with the lowest gradient instead of just those >= 100.

This could also just be working as intended and not intuitive, but it causing trouble when trying to do layer math combines when a layer has techniques set to score of 0.

Navigator version 4.5.5

Steps to recreate:

1) Create new empty layer
2) Set all techniques to score = 0
3) Set some techniques to score = 100
4) Set some other techniques to score = 115
5) Create a gradient set (any colors) with low value = 100 and high value = 115
6) Observe that all techniques that are still 0 are also highlighted with the gradient color instead of just those >= 100

**Comment by clemiller** [comment]
Hi @glennbarrett,

This is the expected behavior for scoring gradients as described in the [Scoring Gradient Usage](https://github.com/mitre-attack/attack-navigator/blob/master/USAGE.md#scoring-gradient) documentation. Techniques with scores below the low value are colored as the low value and techniques with scores above the high value are colored as the high value. All techniques with a score are colored to provide a distinction between a technique with a score and one without. If we removed the coloring for techniques with a score below the score gradient's low value, say a score of 0, we would lose the ability to visually identify whether the technique actually has a score of 0 or if it has no score at all (e.g. maybe it hasn't yet been assessed).

During layer math, techniques without an assigned score are treated as a score of 0 if a score exists on the same technique in the other layer(s). My recommendation would be to leave the techniques unscored and only apply a score to the techniques you're interested in highlighting with a gradient color.

I hope this makes sense!

**Comment by glennbarrett** [comment]
Yep it makes sense! I pre-mark all my scores as zero so that the score line exists in the JSON for some automated layer modification stuff I am doing.  Having them with no score means that the technique doesn't have the score field at all in the JSON.

Thank you for the response anyway!
