### ISSUE TITLE
Highlighting techniques with sub-techniques does not always work as expected

### ISSUE THREAD

**Issue by jcmaton97** [mitre-attack/attack-navigator#471]
When techniques are selected using the selection controls, for example selecting based on threat group, some techniques are not selected which should be.

This seems to be only in some cases where a technique has sub-techniques which are selected, and it's technique is not.

Example: 
Selecting the APT28 threat group, T1204 (User Execution) does not get selected/highlighted despite the fact that T1204.001 and T1204.002 are included when the sub-techniques are expanded.
By contrast T1078 (Valid Accounts) does get selected, where T1078.004 is the only selected sub-technique.

This selection/lack of selection seems arbitrary.

![MITRE technique selection bug](https://user-images.githubusercontent.com/43533625/173851201-645b8c3b-e719-4b61-ab1c-67d20aa8ada3.png)

**Comment by clemiller** [comment]
Hi @jcmaton97,

This is expected behavior. The [ATT&CK Website](https://attack.mitre.org) can be used to identify the techniques that should be selected/highlighted for threat groups. If you refer to the [APT28 threat group page](https://attack.mitre.org/groups/G0007/) and scroll down to the "Techniques Used" section, this contains the full list of techniques that will be selected in the Navigator when you select the APT28 threat group. In reference to your Valid Accounts example, the image below taken from the Website shows that the Valid Accounts technique and only one of its sub-techniques, Cloud Accounts, have been identified as techniques used by APT28, which is why you're seeing this behavior.

![image](https://user-images.githubusercontent.com/48832936/173884926-735523e2-1d3c-487b-a096-bc242122b2c7.png)

In the other example, only the two sub-techniques, Malicious File and Malicious Link, and _not_ their parent technique are listed here.

![image](https://user-images.githubusercontent.com/48832936/173887005-8376501d-460a-4c87-985a-4ccd44540d1f.png)

I hope this helps make sense of how the Navigator is selecting/highlighting techniques.
