### ISSUE TITLE
cors Errors

### ISSUE THREAD

**Issue by cvoth** [mitre-attack/attack-navigator#510]
when trying to create a link to our existing attackjson  to use the process is nearly impossible because a CORS error is created for any link.

a possible solution is to add 
Access-Control-Allow-Origin: *
to the get requests.

**Comment by cvoth** [comment]
Access to XMLHttpRequest at 'http://10.1.1.10/example.json' from origin 'http://10.1.10' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
is the error from the javascript browser.

**Comment by clemiller** [comment]
Hi @cvoth,

It's my understanding that [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) is an [HTTP response header](https://developer.mozilla.org/en-US/docs/Glossary/Response_header), which is essentially metadata attached to the information sent back to a web client when it requests data from a web server. Such headers can only be set server-side (in this case http://10.1.1.10) and are outside of the scope of the Navigator since it is a client-side only application and we cannot modify or manage the web server.

My recommendation would be to save the JSON file to your local machine, rather than pulling from a remote resource. From your post, I'm uncertain what the nature of your JSON file is, but if it is a Navigator layer file, you can upload your local file through the interface under "open existing layer">"upload from local".
