### ISSUE TITLE
MITRE D3fend Navigator Git Repository

### ISSUE THREAD

**Issue by NolatCyber** [mitre-attack/attack-navigator#519]
Hey,

Mitre launched the D3fend framework in the beta version.
Is the navigator going to be available for this too?

**Comment by clemiller** [comment]
Hi @NolatCyber,

ATT&CK has no intent to integrate with the D3fend framework in the near future. Since D3fend is developed and maintained by a completely separate team, I'd recommend reaching out directly to them (d3fend@mitre.org, https://d3fend.mitre.org/contribute/) for more information regarding their future plans.

**Comment by NolatCyber** [comment]
Hey Charissa, thank you for your response.
I will talk to them.
