### ISSUE TITLE
Downloading blank navigator layer 

### ISSUE THREAD

**Issue by jonnieb007secure** [mitre-attack/attack-navigator#530]
I would like to be able to download / export layer and included techniques that have no comments / that have not been scored so that I can do gap analyse reports - is this a feature that exists or can be added? 
Thanks

**Comment by clemiller** [comment]
Hi @jonnieb007secure,

That functionality would be outside the scope of Navigator layers. Layers are intended to only contain the set of annotations (score, color, comment, etc.) that have been added on top of the matrix. The Navigator will omit techniques which have no annotations, which makes layers much smaller since only techniques with annotations need to be included. With over 500 techniques in Enterprise, it would be difficult to work with layer files if they were all included regardless of annotations.

If you're not interested in the annotation side of things, you may want to check out our STIX repositories, which contain the full set of technique data. The layers exported in Navigator will only contain the technique's name and tactic, rather than all of its data.

ATT&CK (STIX 2.0): https://github.com/mitre/cti/
ATT&CK (STIX 2.1): https://github.com/mitre-attack/attack-stix-data

**Comment by jonnieb007secure** [comment]
Thanks will look to do via STIX

**Comment by jonnieb007** [comment]
Hi 
I have looked at STIX and not found an easy way to do, but I have noticed that the export to excel works in the way that I would like layers to work, if you filter for just the platform you want it downloads what is currently in the navigator view (annotated or not) 
So would be great to have a download layer that worked in the same way
Another way to help do this was if the select unannotated only selected the unannotated ones that were visible based on the platform filter, instead of selecting all (including the hidden ones) 
@clemiller is there any way to get these requirements into the backload? Or suggest a developer I could work with? 
Thanks in Advance JB

**Comment by clemiller** [comment]
Hi @jonnieb007,

We have a similar issue open for a feature that sounds related what you're describing - https://github.com/mitre-attack/attack-navigator/issues/215. This issue suggests modifying the download/export functionality to only export annotated techniques which are visible:

![image](https://user-images.githubusercontent.com/48832936/230140990-356dc15f-ed16-4cbf-81eb-21b4ebd10805.png)

This way, I think we could achieve what you're looking for with the following steps:
1. Apply platform filters to the view
2. Select all unannotated techniques and add some set of annotations (i.e. add a color, score, or comment to all selected techniques)
3. Enable the "only download annotations for visible techniques" option and download the layer.

The layer file would include all of the annotated techniques which are visible based on the applied platform filter. Does this sound like it would work for your use case?

**Comment by jonnieb007** [comment]
@clemiller That might work I can add a colour to all unannotated and then just download the visible ones Thanks
