### ISSUE TITLE
Maximum layers allowed.

### ISSUE THREAD

**Issue by pablo97dr** [mitre-attack/attack-navigator#553]
Is there any way to have more than 10 layers opened at the same time?

![imagen](https://user-images.githubusercontent.com/26232468/236278531-46848608-8849-4a54-89f3-047d2572f839.png)

After creating the 10th layer, the "add" button disappears.

![imagen](https://user-images.githubusercontent.com/26232468/236278041-d714d655-2bf9-43c5-95d1-5d70ca47534d.png)

**Comment by clemiller** [comment]
Hi @pablo97dr,

The maximum number of tabs is hardcoded to 10 to avoid performance issues caused by having a large number of layers open at once. Many improvements have been made to the Navigator since then, so it's likely the lagging wouldn't be as extreme at this point. However, we don't currently have plans to increase this number on our live instance. If you are hosting Navigator locally and would like to increase the maximum number of tabs, you can modify the code directly here: `*ngIf="layerTabs.length < 10"` on this line https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/tabs/tabs.component.html#L44.
