### ISSUE TITLE
Add option to show only the disabled techniques

### ISSUE THREAD

**Issue by Cyb3r-Monk** [mitre-attack/attack-navigator#566]
Currenty, it is possible to show/hide `disabled` techniques. It would be nice to have an option to show only the disabled techniques.

**Comment by clemiller** [comment]
Hi @Cyb3r-Monk,

Hiding `enabled` techniques seems like it would be out of scope of the intended use of the Navigator. Since `disabled` techniques do not display manually assigned colors or score colors, annotations wouldn't apply as they would to `enabled` techniques. However, you could achieve this by flipping the `enabled`/`disabled` states of techniques as a workaround:

1. Create a copy of your layer to retain its current state, if needed
2. Select all disabled techniques
3. Click "toggle state" to change their state to `enabled`
4. Right click and select "invert selection" to select all other techniques which had not been marked as `disabled`
5. Click "toggle state" again to mark only those techniques as `disabled`
6. Click "hide disabled techniques"

**Comment by Cyb3r-Monk** [comment]
Thanks for the workaround!
