### ISSUE TITLE
ERROR/BUG when trying to create a customized navigator from URL of layer hosted on the web

### ISSUE THREAD

**Issue by iamgenoveva** [mitre-attack/attack-navigator#568]
Hello! 

I am trying to create a customized navigator in order to get a unique hyperlink that will be able to share with others. The layer I am trying to run is hosted on the web (in Google drive and without viewer/editor restrictions). 

The ERROR I get in the browser when I type the custom navigator URL after adding the google drive URL for the default layer is the following: "ERROR retrieving layer from https://xxx, check the javascript console for more information."

![2023-08-03_13-49-18](https://github.com/mitre-attack/attack-navigator/assets/141328404/70d3457e-a82f-4917-9931-bdde1e9b8634)

Any ideas on how to solve this issue?

Thanks!

**Comment by clemiller** [comment]
Hi @iamgenoveva,

The error you're seeing is a CORS error ([Cross-Origin Resource Sharing](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)), which occurs when a web page hosted on one domain tries to request resources from a different domain. CORS is a security feature implemented to prevent potentially malicious cross-origin requests. In this case, you're trying to load data from a file hosted on Google Drive into your Navigator instance. However, Google Drive restricts cross-origin requests by default, which means that even if the file is publicly accessible, requests to access it from a different origin (your Navigator instance) would be blocked unless Google Drive includes specific CORS headers in its responses.

Since the Navigator is a client-side only application, handling CORS issues becomes more challenging. If you have control over the server that's hosting your file (which may be unlikely since it's a Google service), you might be able to configure it to include the necessary CORS headers in its responses. Alternatively, you may be able to use the Google Drive API directly from the application, which would involve [implementing OAuth 2.0](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow) in your Navigator instance to authenticate and access the file.

If feasible, you might consider hosting the file elsewhere on a server set up with the necessary CORS headers (GitHub, for example).

I hope this helps.
