### ISSUE TITLE
"Cannot GET /" when deploying with Dockerfile.

### ISSUE THREAD

**Issue by 0xShokz** [mitre-attack/attack-navigator#574]
Built an image using the directions in README.  When running a container with the image, errors are displayed to the console followed by a message `** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **`.

When opening the URL in a browser, I get the following error:
`Cannot GET /`

I saw a similar [issue](https://github.com/mitre-attack/attack-navigator/issues/552) from pablo97dr previously, however I am not seeing the file watcher errors.  I am getting this same result trying to build on Windows and on Ubuntu.

[Log file attached](https://github.com/mitre-attack/attack-navigator/files/12489889/2023-08-31.155518.txt)

**Comment by 0xShokz** [comment]
I noticed after a few minutes I received the file watcher limit errors on my Ubuntu machine.  After applying the fix recommended (fs.inotify.max_user_watches=524288) and rebooting, the issue with "Cannot GET /" is still not resolved.  I still have to forcefully stop the container.

**Comment by jorgecastro2** [comment]
@0xShokz did you ever figure out the issue? Tried running the navigator locally and I'm also getting `Cannot GET /`

**Comment by 0xShokz** [comment]
> @0xShokz did you ever figure out the issue? Tried running the navigator locally and I'm also getting `Cannot GET /`

Unfortunately no, so far I have not identified a workaround to resolve the issue using the Dockerfile provided and recommended fixes.

**Comment by FideliusFalcon** [comment]
I was getting a lot of imports errors like:
```
Error: node_modules/@angular/material/paginator/paginator-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
```
And then I was thinking it could be a permission issue. I tried to run as root instead of node, and then I stopped getting the errors, and it worked. But of course this is not security best practice - Then I saw it changes the user to `node`really late in the `Dockerfile` - I tried to change it before the install packages and build and now it worked. 

I have created a pull request for this - https://github.com/mitre-attack/attack-navigator/pull/576

**Comment by mnyethecyberguy** [comment]
This worked for me as well @FideliusFalcon .  Its worth noting I was able to get the app working successfully by using a node container to build the app, and then copying the data over to an nginx alpine image.  The size of the resulting image was substantially smaller at 114MB instead of 1.8GB.
[docker-attack-navigator](https://github.com/mnyethecyberguy/docker-attack-navigator)

**Comment by jorgecastro2** [comment]
@FideliusFalcon Modifying the `Dockerfile` worked for me. Thank you!

**Comment by clemiller** [comment]
The changes mentioned above have been staged on `develop` (https://github.com/mitre-attack/attack-navigator/pull/411) and will be included in the upcoming release next week. Thank you all for your discussion and to @FideliusFalcon for identifying a solution!
