### ISSUE TITLE
How to build project with node version.

### ISSUE THREAD

**Issue by leeliu48307** [mitre-attack/attack-navigator#636]
Hi, I clone this project into my local. run npm install.  Then I got different error message. I just want to know what is the right node, npm, angular/cli version in order to build the project at my local?  Really appreciate it. 

I am working CISA for vulerability.

**Comment by clemiller** [comment]
Hi @leeliu48307,

As specified in the [README](https://github.com/mitre-attack/attack-navigator?tab=readme-ov-file#requirements), Navigator requires Node v16. Node v18 should also work. Navigator is currently using Angular v14.

**Comment by leeliu48307** [comment]
Thank you very much !!

**Comment by leeliu48307** [comment]
Question: My current node version :v20.12.2. When ng version, I got angular:14.2.13. Warning: The current version of Node (20.12.2) is not supported by Angular.  VM system does not have v16 or v18 (I have to maintain or try Node v20).  Then I npm install, I got error message: Resovle could not resolve , while resovling:@angular-builders/custom-webpack@17.0.2 found @angular/compile-cli@14.3.0.  How to fix it? Really appreciate it.

**Comment by clemiller** [comment]
The first issue you're seeing is a warning due to compatibility issues between the Angular and Node versions. Angular v14 does not support Node.js v20, which may cause issues during the installation process. Angular v14 is compatible with Node.js v14 and v16. If it's possible for you to do so on your VM, I'd recommend using `nvm` ([Node Version Manager](https://github.com/nvm-sh/nvm)) to manage and switch between different node versions. We are in the process of upgrading to Angular v17+, but do not currently have a timeline on when that will be released.

The second issue is a dependency resolution error related to `@angular-builders/custom-webpack` and `@angular/compiler-cli`, indicating a mismatch in package versions. This happens when dependencies are not aligned with the Angular version being used. The following steps should help resolve this issue:

1. Clear your npm cache: `npm cache clean --force`
2. Remove existing modules: `rm -rf node_modules`
3. Reinstall dependencies: `npm i`

If the above steps don't resolve your issue, try regenerating the `package-lock.json` file: 
1. Remove the lock file: `rm package-lock.json`
2. Reinstall: `npm i`

**Comment by leeliu48307** [comment]
Thanks for update. I will inform system admin this message, let them to update node v to 16v or 18v.

**Comment by leeliu48307** [comment]
Now I install node v16, angular v14 and run npm install, got the following errors. Any suggestion is high appreciated. 
![20240516_084645](https://github.com/mitre-attack/attack-navigator/assets/23507827/21c6da0a-a1be-415f-9ead-aecbbe153aec)
![20240516_084527](https://github.com/mitre-attack/attack-navigator/assets/23507827/2e2444fb-5c6e-4503-bbcb-68213026e71d)
![20240516_084546](https://github.com/mitre-attack/attack-navigator/assets/23507827/4bfe7491-9394-456e-a465-34c7d35e5c2a)
