### ISSUE TITLE
JSON Export seems buggy

### ISSUE THREAD

**Issue by Dviros** [mitre-attack/attack-navigator#638]
Steps to reproduce:

1. Access Navigator (https://mitre-attack.github.io/attack-navigator/), select Enterprise only with the latest version.
2. Filter out on 365, SaaS, Google Workspace, Azure AD
3. Select T1530 - it appears, state is on.
4. Expand on all techniques and sub-techniques
5. Export as JSON and Excel, search for T1530
6. Technique would appear in the excel file and not in the JSON file

_Originally posted by @OtherPeoplesEnemy in https://github.com/mitre-attack/attack-navigator/issues/630#issuecomment-2057612415_
            
 [layer.xlsx](https://github.com/mitre-attack/attack-navigator/files/15325001/layer.xlsx)
[layer (3).json](https://github.com/mitre-attack/attack-navigator/files/15325002/layer.3.json)

**Comment by clemiller** [comment]
Hi @Dviros,

The JSON download and Excel download have different underlying functions:
- JSON layers are intended to only contain the set of annotations (score, color, comment, etc.) that have been added on top of the matrix. The Navigator will omit techniques which have no annotations from the JSON. This is designed to make the JSON layers much smaller since only techniques with annotations need to be included.
- The Excel download works similarly to the SVG download, where it _renders_ the layer as shown in the Navigator in Excel format.

Since T1530 is visible in the layer, it will be rendered in the Excel file; however, since it is not annotated, it is excluded from the JSON.

Hope this helps! Closing this issue as it appears to be working as expected.
