### ISSUE TITLE
Configure number of opened layers?

### ISSUE THREAD

**Issue by dn2020gh** [mitre-attack/attack-navigator#646]
I understand currently there is a limit of 10 layers being opened at the same time for performance reasons. Is there a configuration variable anywhere to be able to increase that parameter? If yes, can you please advise where it is? If not, is this something that is planned to be considered in future releases as configurable parameter?

**Comment by clemiller** [comment]
Hi @dn2020gh,

Thanks for reaching out. You're correct that the number of open tabs is limited due to performance considerations. This limit was increased from 10 layers to 12 layers last October. At this time, there are no plans to further increase this limit or make it a configuration option. However, we are continuously working on improving the application, and may consider making this configurable in a future release as performance optimizations progress.

If you are hosting the Navigator locally, you do have the option to modify the code directly to increase the layer limit: `*ngIf="hasFeature('tabs') && layerTabs.length < 12"` on this line https://github.com/mitre-attack/attack-navigator/blob/master/nav-app/src/app/tabs/tabs.component.html#L54

**Comment by dn2020gh** [comment]
Hi @clemiller, thank you, I have tested the option and I can open more than 12 layers however I am not presented with the '+' option to then create a new layer from other layers as I wanted to combine them. Is that piece of code controlled somewhere else? Appreciate your help

**Comment by dn2020gh** [comment]
Sorry Charissa, just re-generated docker instance, re-launched, all working now :) Thank you again for your help!

**Comment by clemiller** [comment]
No problem, I’m glad to hear you’ve got it working!
