### ISSUE TITLE
Cannot show matrix and tactics created by myself when integrating ATT&CK Navigator with  ATT&CK Workbench Frontend

### ISSUE THREAD

**Issue by purplezi** [mitre-attack/attack-navigator#650]
Hi ATT&CK Navigator Teams,

Sorry to bother you, but I hope you can help me.

I'm working on the latest navigator and ATT&CK Workbench Frontend v2.1.0 in Ubuntu 22.04 according to this [tutorial](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/integrations.md#attck-navigator-integration). I installed ATT&CK Workbench Frontend using Docker and Navigator through this [guide](https://github.com/mitre-attack/attack-navigator/tree/master?tab=readme-ov-file#install-and-run).

I built my own knowledge base and created new matrix & tactics & techniques. 
I can successfully get the json from `http://localhost:3000/api/stix-bundles/?domain=mobile-attack` (can see from http 200). 

In the navigator I just found the techniques which can be successfully showed in the right sidebar when searching. BUT my matrix and tactics cannot be displayed. 
![IMG_0703](https://github.com/user-attachments/assets/316d72b4-1a1b-46a3-bab9-950470f2687a)

This is what my matrix liked in ATT&CK Workbench Frontend.
![IMG_0704](https://github.com/user-attachments/assets/d57e04ad-667a-4fb9-b287-058bd32d8fbf)

And this is the whole stix-bundles json file. 
![IMG_0706](https://github.com/user-attachments/assets/6674c226-4983-4b33-b9c7-2c0212cfede5)

I don't know how to display my matrix and tactics just like the normal ATT&CK matrices. Any suggestions or solutions for this? 
THANKS for your time again!

**Comment by clemiller** [comment]
Hi @purplezi,

The issue you're seeing is caused by the absence of the `x-mitre-matrix` (Matrix) object in your STIX bundle. The Matrix object is necessary for the Navigator to correctly parse and build the view. Since you are integrating with the Workbench, the matrix is likely not included in the endpoint response because it is missing an ID. In Workbench, if an object does not have an ID, it is considered a draft and will not be included in the published STIX bundle.

I suggest verifying that you have created a Matrix object in your Workbench knowledge base and setting its ID. The ID should be set to your domain (I believe this would be `mobile-attack` based on the `x_mitre_domains` field of the technique and tactic in your bundle). Also, ensure that each Tactic object referenced in `tactic_refs` and each Technique object also have valid IDs and are correctly associated with the `mobile-attack` domain.

After making these adjustments, re-export your STIX bundle and verify that the Matrix object is included. Once the Matrix object is included, the Navigator should be able to display your custom matrix, tactics, and techniques.

**Comment by purplezi** [comment]
It's working!🥳
Thank you for your help and patience!
