### ISSUE TITLE
Offline Installation

### ISSUE THREAD

**Issue by jezkerwin** [mitre-attack/attack-navigator#78]
I'm looking to install the navigator onto a system that doesn't have Internet access.

Is there a way that I can install the navigator using offline methods?

**Comment by isaisabel** [comment]
Hi @jezkerwin,

Here's how you can go about installing the Navigator on your offline machine

# Install prerequisites
1. Install `npm` on the offline machine. I've haven't tried this but my guess is that you would download the installer, transfer to the offline machine and run it. If the installer requires internet access I'd suggest searching on google for better instructions.
2. Install the angular cli using the offline install documentation [here](https://webiks.com/working-offline-with-angular-cli/).

# Install the ATT&CK Navigator
1. Clone the Navigator on your online machine. Run `npm install` from the `nav-app` directory to install the node modules.
2. Download the following files to your `nav-app/src/assets` folder:
2.1. https://raw.githubusercontent.com/mitre/cti/master/mobile-attack/mobile-attack.json
2.2. https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
2.3. https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
3. in `nav-app/src/assets/config.json`, update the following lines: 
   ```
   "enterprise_attack_url": "assets/enterprise-attack.json",
   "pre_attack_url": "assets/pre-attack.json",
   "mobile_data_url": "assets/mobile-attack.json",
   ```
   This will make the Navigator pull its data from the local files we downloaded earlier, instead of from our cti repository.
4. Copy the entire `attack-navigator` folder to your offline machine.
5. Run `ng serve` from the `nav-app`directory to host the Navigator on that machine.

Let us know if this works or if you're still having trouble.

**Comment by mantony52** [comment]
I have the list of MITRE tech IDs which needs to be filtered and to be displayed in the form of different colour in the MITRE navigator. Could you please help me how to achieve this?

**Comment by isaisabel** [comment]
Hi @mantony52,

If you're looking to highlight your set of techniques in the UI I'd recommend creating a layer file with your techniques where each technique has the the `color` property set. This is easily done by hand or via script. Please see the [layer format document](https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv2_2.md) and our [example layer generation script](https://github.com/mitre-attack/attack-navigator/blob/master/layers/attack_layers/attack_layers_simple.py0 for details on how you might achieve this.

**Comment by mantony52** [comment]
Thank you very much @isaisabel . It works.

If I may ask another doubt,  would it be possible to install the ATTACK navigator app inside the Splunk application as a dashboard.Thanks.

**Comment by isaisabel** [comment]
Hi @mantony52,

I'm not aware of any previous attempts to install the Navigator as a Splunk dashboard. I'm not personally familiar with Splunk so I'm not sure whether it would be possible to do. You could always try [embedding it in an iframe](https://github.com/mitre-attack/attack-navigator#embedding-the-navigator-in-a-webpage) (assuming that's supported by Splunk) but that's probably not an ideal solution.

**Comment by payamsamimi** [comment]
Hi @isaisabel,

I have an issue concerning using the Navigator offline, when I want to see the technique description. In the online version of Navigator, it is possible by just right clicking on a technique, and clicking on view technique. But it does not happen in the offline mode in my case. Do you have any idea about it.

**Comment by isaisabel** [comment]
Hi @payamsamimi,

That feature won't work offline because it requires you to connect to the ATT&CK Website. However, you can avoid this by hosting your own instance of the website on the same machine/internal network and adding custom context menu options for the hyperlink.

The ATT&CK Website source code can be found here: https://github.com/mitre-attack/attack-website

If you're on a version less than v3.0 (if you're not using the sub-techniques version), use these instructions for the custom context menu items:
- https://github.com/mitre-attack/attack-navigator#adding-custom-context-menu-options

Otherwise, use these custom context menu instructions since the format changed in v3.0:
- https://github.com/mitre-attack/attack-navigator/tree/develop#adding-custom-context-menu-options

**Comment by payamsamimi** [comment]
Hi @isaisabel,

very thanks for your fast response. 
Adding another service to my environment is unfortunately not so easy. I have only the possilbity to run a service under gitlab pages. However, many thanks for your response.
