### ISSUE TITLE
Scores calculated incorrectly when using * or /

### ISSUE THREAD

**Issue by igthreatmodel** [mitre-attack/attack-navigator#79]
When using "Create Layer from other Layers", the scores are not always calculated correctly.  While a calculation such as a+b works correctly, a*b appears to perform a calculation over multiple values in the source layers rather than operating on the corresponding values for a given technique.  a/b throws an error.

For example, Layer A (a variable) has scores assigned to attacker techniques (assume they are all 100).  Layer B (b variable) has effectiveness scores showing how well different techniques are controlled for.  E.g. A might have "Credential Dumping" assigned a score of 100 and B has it assigned a score of 50 (we can stop it with 50% effectiveness).  If I do a calculation like "a+b", I'll get the result 150 as I'd expect.  But, if I try to combine multiplication and division to show how effectively the technique is mitigated, e.g. "a*((100-b)/100)", it does not work.  

Further experimentation reveals this:

For a control (layer B) with a score of 90, "(100-b)" results in 10 as expected.  

For a control (layer B) with a score of 90, "(100-b)/100" results in .1 as expected.  

For a control (layer B) with a score of 90, and attack (layer A) with a score of 100, "a*(100-b)/100" results in 940!?  (expected result is 10)

For a control (layer B) with a score of 90, and attack (layer A) with a score of 100, "a*(100-b)" results in 94000.  (expected result is 1000)

For the two layers I have created, all of the calculated scores "a*(100-b)/100" are 940 regardless of the scores in Layer B (which vary).  I changed one of the scores in Layer A to be 50 instead of 100 and all the calculated scores in the created sheet dropped to 935.  I changed another score in Layer A to also be 50 and the calculated scores dropped to 885.

I tried a*b and the calculated scores were the same for all techniques that had a score even though their values were not all the same in the source layers.  I tried "a/b" and received: Layer Layer operation error: Matrix must be square (size: [442])

**Comment by isaisabel** [comment]
Hi @igthreatmodel,

The problem is probably with the operator you're using. We use [mathjs](http://mathjs.org) to parse and execute the score expression, and the techniques are converted into a matrix before the conversion. Therefore the `*` [operator](http://mathjs.org/docs/expressions/syntax.html#operators) performs a _matrix multiplication_ operation which is why you're seeing strange values for all the techniques — if the output of the calculation is a single number it assigns them uniformly to all techniques in order to handle cases where the user inputs a constant such as `100`.

Try using the elementwise operations instead. That's `.*` for elementwise-multiply and `./` for elementwise-divide. 

I will open a new issue to document this behavior in the field help for the score expression — it's not terribly obvious and should be made more apparent to users. I think the help page also confusingly uses the wrong operator in one of its examples.

Best wishes,

Isabel
